/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogrosRouteImport } from './routes/logros'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ForosIndexRouteImport } from './routes/foros/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ForosSlugIndexRouteImport } from './routes/foros/$slug/index'
import { Route as ForosSlugThreadIdRouteImport } from './routes/foros/$slug/$threadId'
import { Route as LearnArticlesSlugRouteImport } from './routes/learn/articles/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogrosRoute = LogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ForosIndexRoute = ForosIndexRouteImport.update({
  id: '/foros/',
  path: '/foros/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ForosSlugIndexRoute = ForosSlugIndexRouteImport.update({
  id: '/foros/$slug/',
  path: '/foros/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForosSlugThreadIdRoute = ForosSlugThreadIdRouteImport.update({
  id: '/foros/$slug/$threadId',
  path: '/foros/$slug/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnArticlesSlugRoute = LearnArticlesSlugRouteImport.update({
  id: '/learn/articles/$slug',
  path: '/learn/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logros': typeof LogrosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/perfil': typeof PerfilRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/foros/': typeof ForosIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/foros/$slug/$threadId': typeof ForosSlugThreadIdRoute
  '/learn/articles/$slug': typeof LearnArticlesSlugRoute
  '/foros/$slug/': typeof ForosSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logros': typeof LogrosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/perfil': typeof PerfilRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/foros': typeof ForosIndexRoute
  '/learn': typeof LearnIndexRoute
  '/foros/$slug/$threadId': typeof ForosSlugThreadIdRoute
  '/learn/articles/$slug': typeof LearnArticlesSlugRoute
  '/foros/$slug': typeof ForosSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logros': typeof LogrosRoute
  '/notificaciones': typeof NotificacionesRoute
  '/perfil': typeof PerfilRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/foros/': typeof ForosIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/foros/$slug/$threadId': typeof ForosSlugThreadIdRoute
  '/learn/articles/$slug': typeof LearnArticlesSlugRoute
  '/foros/$slug/': typeof ForosSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logros'
    | '/notificaciones'
    | '/perfil'
    | '/learn/$slug'
    | '/u/$username'
    | '/foros/'
    | '/learn/'
    | '/foros/$slug/$threadId'
    | '/learn/articles/$slug'
    | '/foros/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logros'
    | '/notificaciones'
    | '/perfil'
    | '/learn/$slug'
    | '/u/$username'
    | '/foros'
    | '/learn'
    | '/foros/$slug/$threadId'
    | '/learn/articles/$slug'
    | '/foros/$slug'
  id:
    | '__root__'
    | '/'
    | '/logros'
    | '/notificaciones'
    | '/perfil'
    | '/learn/$slug'
    | '/u/$username'
    | '/foros/'
    | '/learn/'
    | '/foros/$slug/$threadId'
    | '/learn/articles/$slug'
    | '/foros/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogrosRoute: typeof LogrosRoute
  NotificacionesRoute: typeof NotificacionesRoute
  PerfilRoute: typeof PerfilRoute
  LearnSlugRoute: typeof LearnSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  ForosIndexRoute: typeof ForosIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ForosSlugThreadIdRoute: typeof ForosSlugThreadIdRoute
  LearnArticlesSlugRoute: typeof LearnArticlesSlugRoute
  ForosSlugIndexRoute: typeof ForosSlugIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logros': {
      id: '/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof LogrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foros/': {
      id: '/foros/'
      path: '/foros'
      fullPath: '/foros/'
      preLoaderRoute: typeof ForosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foros/$slug/': {
      id: '/foros/$slug/'
      path: '/foros/$slug'
      fullPath: '/foros/$slug/'
      preLoaderRoute: typeof ForosSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foros/$slug/$threadId': {
      id: '/foros/$slug/$threadId'
      path: '/foros/$slug/$threadId'
      fullPath: '/foros/$slug/$threadId'
      preLoaderRoute: typeof ForosSlugThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/articles/$slug': {
      id: '/learn/articles/$slug'
      path: '/learn/articles/$slug'
      fullPath: '/learn/articles/$slug'
      preLoaderRoute: typeof LearnArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogrosRoute: LogrosRoute,
  NotificacionesRoute: NotificacionesRoute,
  PerfilRoute: PerfilRoute,
  LearnSlugRoute: LearnSlugRoute,
  UUsernameRoute: UUsernameRoute,
  ForosIndexRoute: ForosIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  ForosSlugThreadIdRoute: ForosSlugThreadIdRoute,
  LearnArticlesSlugRoute: LearnArticlesSlugRoute,
  ForosSlugIndexRoute: ForosSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
